os: osx
osx_image: xcode11.1
cache: bundler
branches:
  only:
    - master

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=PulsarKit.xcworkspace
  - SCHEME="PulsarKit"
  matrix:
    include:
    - osx_image: xcode11
      env: DESTINATION="OS=13.1,name=iPhone Pro"
    - osx_image: xcode10
      env: DESTINATION="OS=12.1,name=iPhone XS"
    - osx_image: xcode10
      env: DESTINATION="OS=11.4,name=iPhone X"

before_install:
  - echo "BEFORE INSTALL START"
  - gem install bundler
  - echo "BEFORE INSTALL END"
  
script:
  - set -o pipefail
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty
