language: objective-c
osx_image: xcode10.1

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=PulsarKit.xcworkspace
  - FRAMEWORK_SCHEME="PulsarKit"
  matrix:
    - DESTINATION="OS=11.3,name=iPhone X"          SCHEME="$FRAMEWORK_SCHEME"

script:
  - set -o pipefail
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty
