os: osx
cache: bundler
branches:
  only:
    - master

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=PulsarKit.xcworkspace
  - SCHEME="PulsarKit"

matrix:
  include:
  - osx_image: xcode11.2
    env: DESTINATION='OS=13.2.2,name=iPhone 11 Pro Max'
  - osx_image: xcode11.3
    env: DESTINATION='OS=13.3,name=iPhone 11 Pro Max'
  - osx_image: xcode11.4
    env: DESTINATION='OS=13.4,name=iPhone 11 Pro Max'

before_install:
  - echo "BEFORE INSTALL START"
  - gem install xcpretty
  - gem install bundler
  - echo "BEFORE INSTALL END"
  
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty
