# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
language: objective-c
osx_image: xcode7.1

install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- brew update
- brew upgrade xctool

script:
 - pod lib lint
 - xctool -workspace PulsarKit.xcworkspace -scheme 'PulsarKitExample' -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO build