# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)



platform :ios do
 	desc "Release a new version with a patch bump_type"
  	lane :patch do
	    release("patch") # we could use __method__.to_s instead of duplicating the name
  	end

  	desc "Release a new version with a minor bump_type"
  	lane :minor do
	    release("minor")
  	end

  	desc "Release a new version with a major bump_type"
  	lane :major do
	    release("major")
  	end

  	lane :sync do
  		syncRepos
  	end

	def release(type)
		podspec_name = "PulsarKit.podspec"

	   	# Cocoapods Lint
	    pod_lib_lint(allow_warnings: true)
	    version = version_bump_podspec(path: podspec_name, bump_type: type)

	    # Create new Tag
	    git_add(path: podspec_name)
	    git_commit(path: [podspec_name], message: "#{version} release")

	    # Push new tag
	    add_git_tag(tag: "#{version}")
	    push_to_git_remote(remote: "origin", tags: true)

	    # Publish new pod version
    	pod_push(path: podspec_name, allow_warnings: true)
	end

	# def syncRepos
	# 	git_add
	# 	sh("git commit -m'sync'")
	# 	sh("git push origin master")
	# end
end
